### PR TITLE
Scaling-plan: A scaling plan applied to scale the API for professional use-cases

### LINKED ISSUE #16: [Native] Support native libraries for other platforms
Non-intel chipset desktop platforms need support on the `NativeDynamicLibrary`.

### LINKED ISSUE #19: [Scaling-Plan] A plan to scale the API to meet the professional criteria
## The following features are essential: 
- [x] Software Architecture paradigm.

## NativeVariant API:
- [x] An extensible `NativeVariant` API supporting the addition of other variants through the userspace APIs.

## Event Handlers:
- [x] Extraction failure listeners.
- [x] Loading success, and loading failure listeners.
- [x] System found success listener, and system not found listener.

## Anti-failure API:
- [x] Anti-failure interface.
- [x] Anti-failure listeners.

### PR DESCRIPTION
**Pull request by pavly-gerges**
This PR conclusively adds the following to the core API:
- [x] `PlatformPredicate`s: provides the ability to append propositions as platform variant {OS + ARCH + INSTRUCT_SET}.
- [x]  `SystemDetectionListener`s: detects the system found and not found.
- [x]  `ExtractionListener`s: exposes the lifecycle of the extraction process to the user applications.
- [x]  `LoadingListener`s: exposes the lifecycle of the native loading process to the user applications.

In addition, I have updated the `NativeVariant` propositions to reflect the OS ARCHS; according to ChatGPT, the available architectural propositions are:
```
The System.getProperty("os.arch") method in Java returns the operating system architecture. 
Here is a list of possible outputs on various systems and CPUs:

Common Outputs
x86: 32-bit x86 architecture
x86_64: 64-bit x86 architecture, often referred to as amd64
amd64: Another name for x86_64
i386: Another designation for 32-bit x86 architecture
arm: ARM architecture
aarch64: 64-bit ARM architecture
sparc: SPARC architecture
sparcv9: 64-bit SPARC architecture
ppc: PowerPC architecture
ppc64: 64-bit PowerPC architecture
ppc64le: 64-bit PowerPC architecture, little-endian
s390: IBM System/390 architecture
s390x: 64-bit IBM System/390 architecture
riscv32: 32-bit RISC-V architecture
riscv64: 64-bit RISC-V architecture
```

### CODE REVIEW

**Comment by stephengold** [comment]
In addition to the CPUs listed, you may also want to support the 64-bit RISC-V, which must run Java because LWJGL supports it.

**Comment by pavly-gerges** [comment]
> In addition to the CPUs listed, you may also want to support the 64-bit RISC-V, which must run Java because LWJGL supports it.

Thanks, I've considered it. How do you build your native binaries for the Android Operating system? Are you using the Android stock directory paths which are handled directly by the ART, or using customized directory paths inside the Jar files? The current library implementation is not bothered with and ignores customized android directories; as it delegates the Android loading to the ART.

**Comment by stephengold** [comment]
> How do you build your native binaries for the Android Operating system? Are you using the Android stock directory paths which are handled directly by the ART, or using customized directory paths inside the Jar files?

Jolt-jni isn't built for Android yet. I was planning to use customized paths, but could be persuaded otherwise.

Libbulletjme and Minie use the same directory paths that jme3-bullet-native-android used:
+ lib/x86/libbulletjme.so
+ lib/x86_64/libbulletjme.so
+ lib/armeabi-v7a/libbulletjme.so
+ lib/arm64-v8a/libbulletjme.so

**Comment by pavly-gerges** [comment]
> Jolt-jni isn't built for Android yet. I was planning to use customized paths, but could be persuaded otherwise.

In the case you plan for customizing the Android paths, you could open an issue when the time comes for this feature. I don't know the strategy for this implementation, but we will see.

**Comment by pavly-gerges** [comment]
I have deployed a new version to maven-central OSSRH host from this branch build, available now via: 
```java
dependencies {
    implementation "io.github.electrostat-lab:snaploader:1.0.0-beta"
}
```
I've tested the library on Serial4j, everything is working fine on Linux-x86-64 machine. I am very happy that there were no breaking changes to the API apart from migration to the `electrostatic` framework root package names...

I'd like to verify that the library is working fine with Jolt-Jni before proceeding for a full stable release.

For quick testing, you can reference the [`TestBasicFeatures`](https://github.com/Electrostat-Lab/jSnapLoader/blob/scaling-plan/snaploader-examples/src/main/java/electrostatic/snaploader/examples/TestBasicFeatures.java) example updated on this branch, or build something similar to this [extension on Serial4j](https://github.com/Electrostat-Lab/Serial4j/blob/master/serial4j/src/main/java/com/serial4j/util/loader/NativeImageLoader.java), with this minor modification that registers the platform predicates to the loader:
```java
final NativeBinaryLoader loader = new NativeBinaryLoader(libraryInfo);
loader.registerNativeLibraries(new NativeDynamicLibrary[] { DefaultDynamicLibraries.LINUX_X86,
DefaultDynamicLibraries.LINUX_X86_64 }).initPlatformLibrary();
```
EDIT:
Notice that, in case of Jolt-Jni, you have to create a NativeDynamicLibrary object for each variant with a single LibraryInfo object, and then register them all; because the use of `DefaultDynamicLibraries` class is irrelevant in this case.

Here is a quick-start guide: 
```java
// a single library info object defining the platform-independent parts of the library
final LibraryInfo joltInfo =
        new LibraryInfo(null, null, "joltjni", null);
// several platform-dependent native dynamic library objects defining a second level of actualization with platform predicate
final NativeDynamicLibrary[] libraries = new NativeDynamicLibrary[] {
        new NativeDynamicLibrary("linux/x86-64/com/github/stephengold", PlatformPredicate.LINUX_X86_64),
        new NativeDynamicLibrary("linux/x86/com/github/stephengold", PlatformPredicate.LINUX_X86),
        new NativeDynamicLibrary("osx/x86-64/com/github/stephengold", PlatformPredicate.MACOS_X86_64),
        ...
};

// register the platform-dependent libraries
// initialize the library extractor with the required properties and start extraction and loading process
final NativeBinaryLoader loader = new NativeBinaryLoader(joltInfo);
loader.registerNativeLibraries(libraries).initPlatformLibrary(); // register predicates and initialize with the library info
loader.setLoggingEnabled(true);
loader.setRetryWithCleanExtraction(true); // activate the default anti-failure mechanism
try {
    loader.loadLibrary(LoadingCriterion.INCREMENTAL_LOADING); // set the initial loading behavior here
} catch (IOException e) {
    Logger.getLogger(NativeBinaryLoader.class.getName())
            .log(Level.SEVERE, "Jolt-Jni loader has failed!", e);
}
```
This will create a library info object that will aid in locating the current classpath Jar, with the platform directory delegated from the NativeDynamicLibrary object (the second null), and with the same extraction directory as the current user directory (the third null). I hope I can find a better implementation for this confusing part.

**Comment by stephengold** [comment]
In the case of jolt-jni automated testing, the native library isn't in any jar yet. It's in the local filesystem, so no extraction is needed. Can I still use jSnapLoader in this case?

For cases where extraction is needed, a hard-coded directory is risky because it might not be writable. The ideal target directory would be a temporary directory with multiple fallback options. On my Linux box, for instance, LWJGL uses "/tmp/lwjgl_sgold/3.3.2+13/x64". If that's not writable, it falls back on the current working directory ("."). And if that's not writable, it falls back on my home directory ("/home/sgold"). And if that fails, it invokes `getProperty(props, "java.io.tmpdir")` .

**Comment by pavly-gerges** [comment]
> In the case of jolt-jni automated testing, the native library isn't in any jar yet. It's in the local filesystem, so no extraction is needed. Can I still use jSnapLoader in this case?

Yes, you can, with the use of `LoadingCriterion.INCREMENTAL_LOADING`, together with setting-up the right extraction path, you can achieve the trick. jSnapLoader will look for the binary first at the extraction path (defined by the user), then tries to load it, if it doesn't work for whatever reason, a retry crietrion is executed with an interface for user actions, as well.

**Comment by pavly-gerges** [comment]
> For cases where extraction is needed, a hard-coded directory is risky because it might not be writable. The ideal target directory would be a temporary directory with multiple fallback options.

I am not sure if I completely understand you, but the API relies on the user regarding this part, the user defines the extraction path, and the retry criteria that they would like to have. The fallbacks can be designated as anti-failure mechanisms, and it needs to be implemented on the user applications through the `NativeBinaryLoadingListener`s.

**Comment by stephengold** [comment]
> with the use of LoadingCriterion.INCREMENTAL_LOADING, together with setting-up the right extraction path, you can achieve the trick

The correct extraction path for automated testing depends the local operating system. How could my app obtain this information from jSnapLoader, preferably as a `String` value: "linux", "macOS", or "windows"?

**Comment by pavly-gerges** [comment]
> How could my app obtain this information from jSnapLoader, preferably as a `String` value: "linux", "macOS", or "windows"?

Information about the platform providing the runtime is available through the [NativeVariant](https://github.com/Electrostat-Lab/jSnapLoader/blob/scaling-plan/snaploader/src/main/java/electrostatic/snaploader/platform/util/NativeVariant.java) API, it provides a collection for the Java System Properties in namespaces-like classes.

Furthermore, the `PropertiesProvider` provides the rest of system-dependent filesystem properties that could be used to construct platform-specific filesystems (just like I do in Serial4j), but you could also use the Java NIO APIs directly.

**Comment by stephengold** [comment]
I've set up a testbed at https://github.com/stephengold/snap-jolt .

I've successfully tested with Java 21 on Linux. However, there's an issue with older versions of Java that I'd like you to resolve before releasing v1.0 to production. For instance, here's what happens when I test using Java 17:
```console
sgold:~/NetBeansProjects/integration/snap-jolt$ ./gradlew run
Starting a Gradle Daemon, 1 incompatible and 3 stopped Daemons could not be reused, use --status for details

> Task :compileJava FAILED
/home/sgold/NetBeansProjects/integration/snap-jolt/src/main/java/com/github/stephengold/snapjolt/HelloWorld.java:24: error: cannot access LibraryInfo
import electrostatic.snaploader.LibraryInfo;
                               ^
  bad class file: /home/sgold/.gradle/caches/modules-2/files-2.1/io.github.electrostat-lab/snaploader/1.0.0-beta/ab2ff83bceba37641f77298afe4f7195edda846f/snaploader-1.0.0-beta.jar(/electrostatic/snaploader/LibraryInfo.class)
    class file has wrong version 63.0, should be 61.0
    Please remove or make sure it appears in the correct subdirectory of the classpath.

```

**Comment by stephengold** [comment]
I ran the snap-jolt testbed on Linux, MacOS, and Windows using GitHub Actions and Java 21.

+ Not surprisingly, Linux passed.
+ MacOS on ARM passed.
+ MacOS on x86_64 failed:

> System Mac OS X_x86_64 isn't supported yet !

+ Windows failed with a cryptic exception:

```console
> Task :run FAILED
Jul 26, 2024 2:15:41 AM electrostatic.snaploader.NativeBinaryLoader cleanExtractBinary
SEVERE: Extraction has failed!
java.lang.NullPointerException: Cannot invoke "java.io.InputStream.available()" because "libraryStream" is null
	at electrostatic.snaploader.filesystem.FileExtractor.extract(FileExtractor.java:105)
	at electrostatic.snaploader.filesystem.ConcurrentFileExtractor.extract(ConcurrentFileExtractor.java:74)
	at electrostatic.snaploader.NativeBinaryLoader.cleanExtractBinary(NativeBinaryLoader.java:310)
	at electrostatic.snaploader.NativeBinaryLoader.loadLibrary(NativeBinaryLoader.java:162)
	at com.github.stephengold.snapjolt.HelloWorld.main(HelloWorld.java:71)

Error: Exception in thread "main" java.lang.UnsatisfiedLinkError: 'void com.github.stephengold.joltjni.Jolt.registerDefaultAllocator()'
	at com.github.stephengold.joltjni.Jolt.registerDefaultAllocator(Native Method)
	at com.github.stephengold.snapjolt.HelloWorld.main(HelloWorld.java:78)
```

**Comment by pavly-gerges** [comment]
> * Windows failed with a cryptic exception:

This happens at the FileExtractor level; as the FileLocator component has failed to locate the native library inside the Jar file (the zip entry); as a result of the retry criteria. Make sure that you have valid Windows binaries at the specified extraction path and/or inside the stock Jar for a clean extraction, however, you have told me before that you aren't extracting files, so I suppose you have a problem with the windows binaries, either corrupted or not in the correct path.

**Comment by pavly-gerges** [comment]
> * MacOS on x86_64 failed:
> 
> > System Mac OS X_x86_64 isn't supported yet !

I see, this is an indication that no predicates are found for this platform runtime. And, the problem lies within the propositions of this platform object; that is they are evaluated to _false_ in this case. I will see what I can do.

EDIT:
The problem is here: 
```java
    public static final PlatformPredicate MACOS_X86_64 = 
new PlatformPredicate(NativeVariant.Os.isMac() && NativeVariant.Cpu.isAMD() && NativeVariant.Cpu.is64());
```
`NativeVariant.Cpu.isAMD()` this evaluates the whole predicate as _false_, the correction is `isX86()`.

**Comment by pavly-gerges** [comment]
I've released the `1.0.0-gamma` version now with the following: 
* Backward compatibility with earlier Java versions down-to 8.
* Fixed the `PlatformPredicate.MACOS_X86_64` propositions.

Please, consider re-evaluating and reporting back. Thanks for your patience and contribution!

**Comment by pavly-gerges** [comment]
> * Windows failed with a cryptic exception:

In case this happens again, this exception has been replaced with a `FileNotFoundExecption` from the `FileLocator` API as a validation procedure to avoid this cryptic format: 
```java
Jul 26, 2024 8:09:54 AM electrostatic.snaploader.NativeBinaryLoader cleanExtractBinary
SEVERE: Extraction has failed!
java.io.FileNotFoundException: File locator has failed to locate the file inside the compression!
        at electrostatic.snaploader.filesystem.FileLocator.validateFileLocalization(FileLocator.java:97)
        at electrostatic.snaploader.filesystem.FileExtractor.extract(FileExtractor.java:110)
        at electrostatic.snaploader.filesystem.ConcurrentFileExtractor.extract(ConcurrentFileExtractor.java:74)
        at electrostatic.snaploader.NativeBinaryLoader.cleanExtractBinary(NativeBinaryLoader.java:311)
        at electrostatic.snaploader.NativeBinaryLoader.loadLibrary(NativeBinaryLoader.java:163)
        at electrostatic.snaploader.examples.TestBasicFeatures.main(TestBasicFeatures.java:77)
```
It's reproducible by two ways: 
* Trying to locate and extract a file that is not present in a compression.
* Trying to load a library that is not present in the extraction path with an activated default retry criterion which retries with a clean extraction, hence, the stack will be directed to the former stack, so these are deterministic in order.

EDIT:
This will be available on the next testing version (typically the `delta` version).

**Comment by stephengold** [comment]
> you have told me before that you aren't extracting files, so I suppose you have a problem with the windows binaries, either corrupted or not in the correct path.

For automated testing in the jolt-jni project, there's no need to extract files, because they're already present in the filesystem. However, the failures I reported are in the snap-jolt project, which does extraction: https://github.com/stephengold/snap-jolt/blob/f8fc077da82294bd80bbd47da97001101a80bbe6/src/main/java/com/github/stephengold/snapjolt/HelloWorld.java#L59-L74

Sorry for the confusion.

> This happens at the FileExtractor level; as the FileLocator component has failed to locate the native library inside the Jar file (the zip entry); as a result of the retry criteria. Make sure that you have valid Windows binaries at the specified extraction path and/or inside the stock Jar for a clean extraction 

It turns out there's a valid Windows binary in the platform directory, but its name is incorrect:

```console
$ jar tf jolt-jni-Windows64-0.3.2-DebugSp.jar
META-INF/
META-INF/MANIFEST.MF
windows/x86-64/com/github/stephengold/joltjni.dll
```

The final component of the path should be "libjoltjni.dll" instead "joltjni.dll".

This mistake doesn't pose any difficulty for JME's `NativeLibraryLoader`, because the complete path is specified:
https://github.com/stephengold/kk-physics/blob/cfe378bd3eb5de1c96c11e71082514e8a88bf834/library/src/main/java/com/jme3/bullet/util/NativeLibrary.java#L90-L92

JSnapLoader's way (specifying only the platform directory) is superior to that of `NativeLibraryLoader` in most cases. However, when the extraction fails the JSnapLoader message should include the complete path. That would simplify troubleshooting.
 
I'll correct the name of the Windows binary in jolt-jni and try again.

**Comment by pavly-gerges** [comment]
Thanks for this comprehension. So far I will try to provide the `NativeDynamicLibrary` with an extra constructor that enables the user APIs to assign the full name themselves, that way the issue will be resolved without changes in Jolt-jni building script.

**Comment by stephengold** [comment]
No, wait! I got it backward:
+ The names of Linux shared libraries always begin with "lib". For example, "libbulletjme.so".
+ The names of Windows shared libraries usually don't. So "joltjni.dll" is a valid native library name.

**Comment by pavly-gerges** [comment]
So, should we just selectively remove the prefixed value "lib" before the windows binaries in the `NativeDynamicLibrary` as a matter of windows DLLs standardizations?

**Comment by stephengold** [comment]
> So, should we just selectively remove the prefixed value "lib" before the windows binaries in the `NativeDynamicLibrary` as a matter of windows DLLs standardizations?

Yes, I think so:
```diff
--- a/snaploader/src/main/java/com/avrsandbox/snaploader/platform/NativeDynamicLibrary.java
+++ b/snaploader/src/main/java/com/avrsandbox/snaploader/platform/NativeDynamicLibrary.java
@@ -105,8 +105,8 @@
             NativeDynamicLibrary.LINUX_x86_64.library = "lib" + libraryInfo.getBaseName() + ".so";
             NativeDynamicLibrary.MAC_x86.library = "lib" + libraryInfo.getBaseName() + ".dylib";
             NativeDynamicLibrary.MAC_x86_64.library = "lib" + libraryInfo.getBaseName() + ".dylib";
-            NativeDynamicLibrary.WIN_x86.library = "lib" + libraryInfo.getBaseName() + ".dll";
-            NativeDynamicLibrary.WIN_x86_64.library = "lib" + libraryInfo.getBaseName() + ".dll";
+            NativeDynamicLibrary.WIN_x86.library = libraryInfo.getBaseName() + ".dll";
+            NativeDynamicLibrary.WIN_x86_64.library = libraryInfo.getBaseName() + ".dll";
         }
         
         /* Initializes the library jar path to locate before extracting, "null" to use the classpath */
```

However, it would also be prudent to provide some mechanism for specifying the full name.

**Comment by stephengold** [comment]
> this evaluates the whole predicate as _false_, the correction is `isX86()`.

I can confirm that this correction (in the gamma pre-release) solves the issue with MACOS_X86_64:

https://github.com/stephengold/snap-jolt/actions/runs/10114683678/job/27973857208

**Comment by pavly-gerges** [comment]
> I think so:
> 
> ```diff
> --- a/snaploader/src/main/java/com/avrsandbox/snaploader/platform/NativeDynamicLibrary.java
> +++ b/snaploader/src/main/java/com/avrsandbox/snaploader/platform/NativeDynamicLibrary.java
> @@ -105,8 +105,8 @@
>              NativeDynamicLibrary.LINUX_x86_64.library = "lib" + libraryInfo.getBaseName() + ".so";
>              NativeDynamicLibrary.MAC_x86.library = "lib" + libraryInfo.getBaseName() + ".dylib";
>              NativeDynamicLibrary.MAC_x86_64.library = "lib" + libraryInfo.getBaseName() + ".dylib";
> -            NativeDynamicLibrary.WIN_x86.library = "lib" + libraryInfo.getBaseName() + ".dll";
> -            NativeDynamicLibrary.WIN_x86_64.library = "lib" + libraryInfo.getBaseName() + ".dll";
> +            NativeDynamicLibrary.WIN_x86.library = libraryInfo.getBaseName() + ".dll";
> +            NativeDynamicLibrary.WIN_x86_64.library = libraryInfo.getBaseName() + ".dll";
>          }
>          
>          /* Initializes the library jar path to locate before extracting, "null" to use the classpath */
> ```

Beware that the classes on the current master are internally different from the current branch; the API has recently undergone a lot of changes, but with preservation of the method signatures, so no breaking changes so far.

**Comment by pavly-gerges** [comment]
Alright, version `1.0.0-delta` is now available with the following changelog: 
- _FileLocalizingListener_ interface to bind user APIs to the FileLocator API lifecycle.
- Validation of the _FileLocator_ streams at the _FileLocator_ levels with the suppression with business exceptions to avoid cryptic formats.
- _`NativeDynamicLibrary.<init>(...)`_: allows for full directory path designation by overwriting the basename from `LibraryInfo`.
- _NativeDynamicLibrary#initPlatformLibrary(LibraryInfo)_: removed the prefixed value `lib` for Windows runtime as a part of the standardization of Windows DLL files.

**Comment by stephengold** [comment]
I've updated my projects to 1.0.0-delta: both the snap-jolt testbed and also automated tests in the jolt-jni project. All tests are passing.

The loading code in jolt-jni is rather crude. I'd welcome any suggestions you might have for simplifying or refining it:

https://github.com/stephengold/jolt-jni/blob/6d49e4847de148b5cd137bc93c363fb905d8d23b/src/test/java/testjoltjni/TestUtils.java#L240-L263

I'm thinking about how to test jSnapLoader on Linux-on-ARM platforms. I have a 32-bit Raspberry Pi on my desk plus remote access to 64-bit build servers at Travis-CI. Libbulletjme is already built for Linux-on-ARM but jolt-jni currently is not.

**Comment by pavly-gerges** [comment]
> I have a 32-bit Raspberry Pi on my desk plus remote access to 64-bit build servers at Travis-CI. Libbulletjme is already built for Linux-on-ARM but jolt-jni currently is not.

Well, if you have any TestBullets techdemos (on Libbulletjme or even jme3-examples), you could plug them on with jSnapLoader. However, I don't know how you will suppress the JME's NativeLibraryLoader...

**Comment by pavly-gerges** [comment]
> The loading code in jolt-jni is rather crude. I'd welcome any suggestions you might have for simplifying or refining it:
> 
> https://github.com/stephengold/jolt-jni/blob/6d49e4847de148b5cd137bc93c363fb905d8d23b/src/test/java/testjoltjni/TestUtils.java#L240-L263

In case you accept contributions, could you activate running the GitHub workflows for PRs against master, please? 

So, something like: 
```yml
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
```
Then, we could test the changes remotely on GitHub before merging.

**Comment by stephengold** [comment]
Good point about suppressing JME's loader.

Luckily, I have many Libbulletjme demos and tests that don't use JMonkeyEngine at all. Instead of extracting native libraries from JARs (as Minie, KK Physics, and jolt-jni do), those apps download native libraries from GitHub Releases via HTTPS (because Libbulletjme natives aren't currently available from Maven Central).

There's [an open issue to publish Libbulletjme natives to MavenCentral](https://github.com/stephengold/Libbulletjme/issues/12). If I solved that, I could use Libbulletjme to test extraction.

Ideally I should both solve https://github.com/stephengold/Libbulletjme/issues/12 *and* publish Linux-on-ARM natives for jolt-jni. Then I could test jSnapLoader extraction on Linux-on-ARM using both libraries. But it's difficult to predict how long those changes might take. A week or two, maybe.

Are you willing to delay the stable release of jSnapLoader v1.0 by a couple weeks, to allow for additional testing?

**Comment by pavly-gerges** [comment]
> Are you willing to delay the stable release of jSnapLoader v1.0 by a couple weeks, to allow for additional testing?

Yes, sure, I am not on a hurry. Since, the `delta` has proven efficiency, the `stable` release will not add that much, so we could wait until full testing is done.

**Comment by stephengold** [comment]
> could you activate running the GitHub workflows for PRs against master, please?

I've done so, both in jolt-jni and snap-jolt.

**Comment by pavly-gerges** [comment]
> I've done so, both in jolt-jni and snap-jolt.

Thanks! I propose to merge this PR, and continue on forums.

**Comment by pavly-gerges** [comment]
@stephengold Your contributions are much appreciated! Thank you!

**Pull request merged**
